packages:
  - "artifacts/*"
  - "lib/*"
  - "scripts"

allowBuilds:
  '@google/genai': set this to true or false
  esbuild: true
  ffmpeg-static: set this to true or false
  protobufjs: set this to true or false
